<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop Our Products</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        header {
            background-color: #333;
            color: white;
            padding: 20px 0;
            text-align: center;
        }

        nav {
            background-color: #444;
            padding: 10px;
            text-align: center;
        }

        nav a {
            color: white;
            text-decoration: none;
            margin: 0 15px;
        }

        nav a:hover {
            background-color: #555;
        }

        .product-list {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
            padding: 20px;
        }

        .product {
            background-color: white;
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 20px;
            width: 250px;
            margin: 15px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }

        .product img {
            width: 100%;
            height: auto;
        }

        .product h3 {
            font-size: 1.2em;
            margin: 15px 0;
        }

        .product p {
            font-size: 1em;
            color: #666;
        }

        .product .price {
            font-size: 1.5em;
            font-weight: bold;
            color: #27ae60;
            margin: 10px 0;
        }

        .button {
            background-color: #3498db;
            color: white;
            padding: 10px;
            border: none;
            cursor: pointer;
            width: 100%;
            text-align: center;
            border-radius: 5px;
        }

        .button:hover {
            background-color: #2980b9;
        }

        footer {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 10px 0;
            position: fixed;
            width: 100%;
            bottom: 0;
        }
    </style>
</head>
<body>

    <!-- Header -->
    <header>
        <h1>Welcome to Our Shop</h1>
    </header>

    <!-- Product Listings -->
    <div class="product-list" id="shop">
        <!-- Product 1 -->
        <div class="product">
            <img src="https://via.placeholder.com/250" alt="Product 1">
            <h3>Account </h3>
            <p>Account With SG CDK TTK MAX LEVEL RANDOM RACE V4</p>
            <div class="price">$20.00</div>
            <button class="button" onclick="window.location.href='https://www.paypal.com/invoice/p/#EWYUBEQZTV3LRJ9R'">Buy Now</button>
        </div>

        <!-- Product 2 -->
        <div class="product">
            <img src="https://via.placeholder.com/250" alt="Product 2">
            <h3>Race V4</h3>
            <p>This product is perfect for special occasions.</p>
            <div class="price">$50.00</div>
            <button class="button" onclick="window.location.href='https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=YOUR_BUTTON_ID_2'">Buy Now</button>
        </div>

        <!-- Product 3 -->
        <div class="product">
            <img src="https://via.placeholder.com/250" alt="Product 3">
            <h3>Sanguine</h3>
            <p>For those who need high-quality performance.</p>
            <div class="price">$30.00</div>
            <button class="button" onclick="window.location.href='https://www.paypal.com/invoice/p/#EWYUBEQZTV3LRJ9R'">Buy Now</button>
        </div>
    </div>

    <!-- Footer -->
    <footer>
        <p>&copy; 2025 Our Shop. All rights reserved.</p>
    </footer>

</body>
</html>
